# Generated by Django 5.2.8 on 2025-11-28 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '__first__'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tasks.task')),
            ],
            options={
                'unique_together': {('task', 'employee', 'client')},
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('photo_answer', models.ImageField(blank=True, null=True, upload_to='survey_photos/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.surveyquestion')),
                ('selected_choices', models.ManyToManyField(blank=True, to='tasks.surveychoice')),
                ('task_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='feedback.taskresponse')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoReportResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('equipment_count', models.IntegerField(blank=True, null=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='photo_reports/')),
                ('comment', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('task_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo_report_response', to='feedback.taskresponse')),
            ],
        ),
    ]
