# Generated by Django 5.2.8 on 2025-11-28 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Текстовое поле'), ('single_choice', 'Список с единичным выбором'), ('multiple_choice', 'Список с множественным выбором'), ('single_checkbox', 'Чекбокс с единичным выбором'), ('multiple_checkbox', 'Чекбокс с множественным выбором'), ('photo', 'Фото')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='tasks.surveyquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('survey', 'Анкета'), ('photo_report_stand', 'Фотоотчет по стендам'), ('photo_report_simple', 'Фотоотчет простой')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлено'), ('in_progress', 'На доработке'), ('completed', 'Выполнено')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_count', models.IntegerField(blank=True, help_text="План по количеству анкет (для задач типа 'Анкета')", null=True)),
                ('assigned_client_groups', models.ManyToManyField(blank=True, related_name='assigned_tasks', to='clients.clientgroup')),
                ('assigned_clients', models.ManyToManyField(blank=True, related_name='assigned_tasks', to='clients.client')),
                ('assigned_employee_groups', models.ManyToManyField(blank=True, related_name='assigned_tasks', to='accounts.employeegroup')),
                ('assigned_employees', models.ManyToManyField(blank=True, limit_choices_to={'role': 'employee'}, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['moderator', 'super_moderator']}, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='task',
            field=models.ForeignKey(limit_choices_to={'task_type': 'survey'}, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tasks.task'),
        ),
        migrations.CreateModel(
            name='PhotoReportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('task', models.OneToOneField(limit_choices_to={'task_type__in': ['photo_report_stand', 'photo_report_simple']}, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлено'), ('in_progress', 'На доработке'), ('completed', 'Выполнено')], default='sent', max_length=20)),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'unique_together': {('task', 'employee')},
            },
        ),
    ]
